# Generated by Django 5.1.7 on 2025-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbeta', '0004_carrental_flight_hotel_shortlet_vacation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='exclusions',
            field=models.TextField(blank=True, help_text="List what's not included in the package"),
        ),
        migrations.AddField(
            model_name='vacation',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='vacations/'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='vacations/'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='inclusions',
            field=models.TextField(blank=True, help_text="List what's included in the package"),
        ),
        migrations.AddField(
            model_name='vacation',
            name='itinerary',
            field=models.TextField(blank=True, help_text='Day-by-day itinerary details'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='number_of_nights',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vacation',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='room_type',
            field=models.CharField(blank=True, help_text='e.g. Deluxe, Suite, etc.', max_length=100),
        ),
    ]
