# Generated by Django 5.1.7 on 2025-03-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbeta', '0005_vacation_departure_date_vacation_exclusions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='category',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Suv', 'SUV'), ('Luxury', 'Luxury'), ('Van', 'Van')], max_length=20),
        ),
    ]
