# Generated by Django 5.1.7 on 2025-03-31 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbeta', '0006_alter_carrental_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('flight_class', models.CharField(blank=True, choices=[('economy', 'Economy'), ('premium', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class')], max_length=20)),
                ('query_payload', models.JSONField(blank=True, null=True)),
                ('amadeus_response', models.JSONField(blank=True, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to='travelbeta.profile')),
            ],
        ),
    ]
